### ISSUE TITLE
macaca-datahub@2.3.11: DataHub start unsuccessfully: Error: Command failed: sequelize db:migrate

### ISSUE THREAD

**Issue by imjenny** [macacajs/macaca-datahub#123]
C:\Users\lee>npm i macaca-datahub -g
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
C:\Users\lee\AppData\Roaming\npm\datahub -> C:\Users\lee\AppData\Roaming\npm\node_modules\macaca-datahub\bin\datahub.js
C:\Users\lee\AppData\Roaming\npm\macaca-datahub -> C:\Users\lee\AppData\Roaming\npm\node_modules\macaca-datahub\bin\datahub.js
+ macaca-datahub@2.3.11
updated 6 packages in 65.269s

C:\Users\lee>datahub server

DataHub start unsuccessfully: Error: Command failed: C:\Users\lee\AppData\Roaming\npm\node_modules\macaca-datahub\node_modules\sequelize-cli\lib\sequelize db:migrate
C:\Users\lee\AppData\Roaming\npm\node_modules\macaca-datahub\.sequelizerc:7
  'migrations-path': path.join(__dirname, 'database, 'migrations'),
                                          ^^^^^^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadRCFile (C:\Users\lee\AppData\Roaming\npm\node_modules\macaca-datahub\node_modules\sequelize-cli\lib\core\yargs.js:27:78)

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-datahub/commit/3c9d3b3295ff23f6d47b0499680c416e021a52e8
