### ISSUE TITLE
datahub server提示js错误

### ISSUE THREAD

**Issue by chenweik** [macacajs/macaca-datahub#132]
# datahub server
/usr/lib/node_modules/macaca-datahub/bin/datahub-server.js:47
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by zhangyuheng** [comment]
`node -v` 看下版本是什么，如果小于 8 可以安装升级下

**Comment by chenweik** [comment]
升级到v11.10.1后，提示
Please install sqlite3 package manually

安装sudo npm install sqlite3 -g后，仍旧提示
DataHub start unsuccessfully: Error: Command failed: /usr/lib/node_modules/macaca-datahub/node_modules/sequelize-cli/lib/sequelize db:migrate
ERROR: Please install sqlite3 package manually

Sequelize CLI [Node: 11.10.1, CLI: 4.1.1, ORM: 4.43.0]

Loaded configuration file "database/config.js".

**Comment by zivyangll** [comment]
@chenweik 重装 node_modules 就可以了
