### ISSUE TITLE
接口名称相同报错

### ISSUE THREAD

**Issue by boychina** [macacajs/macaca-datahub#68]
我创建了两个项目，恰巧两个项目中的接口名称有重复的情况。第二个项目中新建对应的接口的时候，页面没有任何内容。
打开控制台发现报500的错误。
按理来说两个项目名字本身不相同，已经决定了不存在接口冲突的情况。
![image](https://user-images.githubusercontent.com/20528499/43125530-e5bf2d02-8f5c-11e8-80fe-691297289653.png)

以下是报错信息：
SequelizeUniqueConstraintError: Validation error
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/admin/.nvm/versions/node/v8.9.4/lib/node_modules/macaca-datahub/node_modules/_sequelize@4.37.7@sequelize/lib/dialects/sqlite/query.js:417:16)
    at Statement.afterExecute (/home/admin/.nvm/versions/node/v8.9.4/lib/node_modules/macaca-datahub/node_modules/_sequelize@4.37.7@sequelize/lib/dialects/sqlite/query.js:119:32)
    at Statement.replacement (/home/admin/.nvm/versions/node/v8.9.4/lib/node_modules/macaca-datahub/node_modules/_sqlite3@3.1.13@sqlite3/lib/trace.js:19:31)

**Comment by boychina** [comment]
OK, Thank you for your efforts!

**Comment by zhangyuheng** [comment]
@boychina  You can use v2 now `"macaca-datahub": "^2.0.0",`
before start, remove db `rm -rf ~/.macaca-datahub/macaca-datahub.data`

**Comment by boychina** [comment]
OK, Thank you!
